### ISSUE TITLE
Black and isort pre-commit-config

### ISSUE THREAD

**Issue by a-cid** [pronovic/apologies#38]
Hey, thanks for this repo, really helped me out setting up poetry+precommit on my project.

However I'd like to suggest altering the black and isort configs in .pre-commit-config.yaml to be as follows:
  
    repos:
      - repo: local
        hooks:
          - id: system
            name: Black
            entry: poetry run black
            types: [python]
            language: system
      - repo: local
        hooks:
          - id: system
            name: isort
            entry: poetry run isort
            types: [python]
            language: system

this way these checks only run on files staged for commit, which saves a lot of headaches during code refactoring

and if you'd like to run pre-commit on your entire project, you can run `pre-commit run --all-files`

**Comment by pronovic** [comment]
I'm glad you've found apologies useful.

I appreciate the suggestion.  Over time, I've established that that I prefer the result when all of the pre-commit steps operate on all files all the time.  Among other reasons, it ensures that my local checks are doing exactly the same thing as the checks in the GitHub Actions build, so I don't get any surprises there.

However, I agree that this behavior can sometimes be annoying , especially if I want to do incremental commits into a PR branch on partially-complete code.  In that situation, many of the pre-commit hooks can be problematic &mdash; both black and isort as well as pylint and mypy.  I tend to use `run check` to run the checks manually, so I at least know what's in a bad state.  Then, I do my incremental commits with `--no-verify`, to temporarily skip the  pre-commit hooks altogether.  As long as I fix all of the problems in my local branch before pushing to GitHub, I don't get a failed PR build in GitHub Actions.  And, I always squash-merge my PRs, so those incremental commits that don't meet the code quality standards never end up in the master branch.

Anyway, I want to keep apologies in its current state, because the current pattern is one I've a bunch of other repos that I maintain here and at work.  However, I will add some additional notes into the `DEVELOPER.md` file to describe your changes above as an alternative approach.
